[platformio]
default_envs = esp32dev, esp32s3, esp32c3

[env]
platform = espressif32@^6.9.0
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  h2zero/NimBLE-Arduino@^1.4.3
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DROADLENS_FIRMWARE_VERSION=\"0.1.10\"

[env:esp32dev]
board = esp32dev
build_flags =
  ${env.build_flags}
  -DROADLENS_CHIP_FAMILY=\"ESP32\"
  -DROADLENS_OTA_URL=\"https://its-ze.github.io/roadlens-scout/flasher/firmware/esp32/firmware.bin\"

[env:esp32s3]
board = esp32-s3-devkitc-1
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DROADLENS_CHIP_FAMILY=\"ESP32-S3\"
  -DROADLENS_OTA_URL=\"https://its-ze.github.io/roadlens-scout/flasher/firmware/esp32s3/firmware.bin\"

[env:esp32c3]
board = esp32-c3-devkitm-1
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DROADLENS_CHIP_FAMILY=\"ESP32-C3\"
  -DROADLENS_OTA_URL=\"https://its-ze.github.io/roadlens-scout/flasher/firmware/esp32c3/firmware.bin\"
