[platformio]
default_envs = esp32dev, esp32s3, esp32c3

[env]
platform = espressif32@^6.9.0
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  h2zero/NimBLE-Arduino@^1.4.3
build_flags =
  -DCORE_DEBUG_LEVEL=1

[env:esp32dev]
board = esp32dev

[env:esp32s3]
board = esp32-s3-devkitc-1
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

[env:esp32c3]
board = esp32-c3-devkitm-1
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
